# Generated by Django 3.0.6 on 2020-05-14 00:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Physics'), ('1', 'Geometry'), ('2', 'Social Studies'), ('3', 'Chemistry')], max_length=7),
        ),
    ]
