# Generated by Django 3.0.6 on 2020-05-14 14:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200514_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PHYSICS', 'Physics'), ('GEOMETRY', 'Geometry'), ('SOCIAL_STUDIES', 'Social Studies'), ('CHEMISTRY', 'Chemistry'), ('LANGUAGE_ARTS', 'Language Arts'), ('ENGLISH', 'English'), ('WORLD_LITERATURE', 'World Literature'), ('JOURNALISM', 'Journalism'), ('PAINTING', 'Painting'), ('SCULPTURE', 'Sculpture'), ('DRAWING', 'Drawing'), ('PROGRAMMING', 'Programming'), ('PHOTOSHOP', 'Photoshop'), ('WEB_DESIGN', 'Web Design'), ('HEALTH', 'Health')], max_length=158),
        ),
    ]
